---
title: "Terni distribuzione traccianti"
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

{
  # library(sf)
  #library(dplyr)
  library(ggplot2)
  library(chron)
  library(readxl)
library(terra)
library("sf")
library(sp)
library(raster)
library(tidyverse)
library(dplyr)
library(lubridate)
library(ggmap) # for fancy plotting
library(geoR)
library(gstat)
# library(ggregplot)
library(RColorBrewer)
library(vtable)
library(glue)
library(kableExtra)
 

} 
setwd("/mnt/discoring/terni-inla")

# pltnts <- names(elements_data_rev)[17:87]
# pltnts <- grep("^[M-Z]", pltnts, value = TRUE) 
var_y <- readRDS("data/var_y.RDS")
# Load shapefile
nc <- st_read("data/shp/punti_misura.shp")
terni <- st_read("data/shp/Terni_sez.shp")

# Plot it without converting geometry to x, y columns
coordinate_terni <- st_centroid(nc)
st_coordinate_terni <- st_coordinates(nc)


```


```{r, results='asis', message=FALSE,echo=FALSE, warning=FALSE}

for (poll in var_y){
  #poll <- 'Cr_i'
  if (poll!='Brake_Dust_CR'){
  cat("\n## ", poll, "\n\n")
  df <- readRDS(glue::glue("data/rds_finali/{poll}_df.RDS"))
  df  <- inner_join(df , coordinate_terni, by = c('site' = 'Site'))
  df  <- df  %>%
    mutate(x = unlist(map(df$geometry, 1)),
           y = unlist(map(df$geometry, 2)))
 #df$log_value <- map_dfr(df, function(x) replace(x, is.infinite(x), NA)  )
 df$log_value[sapply(df$log_value, is.infinite)] <- NA
# EDA ----
# hist(df$value)
# hist(df$log_value)
st(df,labels =poll,vars = c('value'))  
 
ggplot(df,aes(x=value)) +
  geom_histogram(fill="red", binwidth = function(x) 2 * IQR(x) / (length(x)^(1/3)),alpha=0.5)+
    ggtitle(poll) -> g
  print(g)
  
  cat("\n\n")
  
 test <- shapiro.test(df$log_value)
ggplot(df,aes(x=log_value)) +
  geom_histogram(fill="blue", binwidth = function(x) 2 * IQR(x) / (length(x)^(1/3)),alpha=0.5)+
   ggtitle(poll) -> g
  #+
  # annotate(geom="text",  col="red", hjust=1,  y=20, x =20,
  #          label=paste("atop(' W: '*",test$statistic,",' p-value: '*",test$p.value,")"), parse=T)-> g

 print(g)
  
  cat("\n\n")
  print(test)
  qqnorm(df$log_value);  qqline(df$log_value, col="green", lwd=2)
   cat("\n\n")
  }
}
```



